"""remove session relation from submitted answer

Revision ID: 78c9d8596db4
Revises: 9a429f208192
Create Date: 2026-04-13 16:25:33.042328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78c9d8596db4'
down_revision: Union[str, Sequence[str], None] = '9a429f208192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluationresult', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_evaluationresult_submitted_answer_id'), table_name='evaluationresult')
    op.alter_column('message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_index(op.f('ix_message_session_id'), table_name='message')
    op.alter_column('quizitem', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_quizitem_quiz_request_id'), table_name='quizitem')
    op.alter_column('quizrequest', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('quizrequest', 'status',
               existing_type=postgresql.ENUM('PENDING', 'GENERATED', 'COMPLETED', name='quizstatus'),
               nullable=False)
    op.drop_index(op.f('ix_quizrequest_session_id'), table_name='quizrequest')
    op.alter_column('submittedanswer', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_submittedanswer_quiz_item_id'), table_name='submittedanswer')
    op.drop_index(op.f('ix_submittedanswer_session_id'), table_name='submittedanswer')
    op.drop_constraint(op.f('submittedanswer_session_id_fkey'), 'submittedanswer', type_='foreignkey')
    op.drop_column('submittedanswer', 'session_id')
    op.alter_column('usersession', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('usersession', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'ARCHIVED', 'DELETED', name='sessionstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersession', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'ARCHIVED', 'DELETED', name='sessionstatus'),
               nullable=True)
    op.alter_column('usersession', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('submittedanswer', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('submittedanswer_session_id_fkey'), 'submittedanswer', 'usersession', ['session_id'], ['id'])
    op.create_index(op.f('ix_submittedanswer_session_id'), 'submittedanswer', ['session_id'], unique=False)
    op.create_index(op.f('ix_submittedanswer_quiz_item_id'), 'submittedanswer', ['quiz_item_id'], unique=False)
    op.alter_column('submittedanswer', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_quizrequest_session_id'), 'quizrequest', ['session_id'], unique=False)
    op.alter_column('quizrequest', 'status',
               existing_type=postgresql.ENUM('PENDING', 'GENERATED', 'COMPLETED', name='quizstatus'),
               nullable=True)
    op.alter_column('quizrequest', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_quizitem_quiz_request_id'), 'quizitem', ['quiz_request_id'], unique=False)
    op.alter_column('quizitem', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_message_session_id'), 'message', ['session_id'], unique=False)
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.alter_column('message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_evaluationresult_submitted_answer_id'), 'evaluationresult', ['submitted_answer_id'], unique=False)
    op.alter_column('evaluationresult', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
