"""upgrade depricated utc_now function to latest method

Revision ID: 8049f5d4763c
Revises: cb3990e6a961
Create Date: 2026-04-13 19:37:40.514222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8049f5d4763c'
down_revision: Union[str, Sequence[str], None] = 'cb3990e6a961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
